SELECT
    LEAST(w1.WORKER_ID, w2.WORKER_ID) AS WORKER_ID1,
    GREATEST(w1.WORKER_ID, w2.WORKER_ID) AS WORKER_ID2
FROM
    WORKTIME w1
JOIN
    WORKTIME w2
    ON w1.ID < w2.ID
    AND w1.ENTER_AT = w2.ENTER_AT
    AND w1.LEAVE_AT = w2.LEAVE_AT
ORDER BY
    WORKER_ID1,
    WORKER_ID2;